apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.name | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
