apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-scripts
data:
{{- range $path, $_ := (.Files.Glob "sql/*") }}
  {{ trimPrefix "sql/" $path }}: |
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{ end }}