apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres-statefulset
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "klustercost.componentSelectorLabels" (dict "context" . "component" "postgres") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "klustercost.componentLabels" (dict "context" . "component" "postgres") | nindent 8 }}
    spec:
      {{- if .Values.imageRegistry.enabled }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-registry-secret
      {{- end }}
      {{- if .Values.postgresql.tls.enabled }}
      securityContext:
        fsGroup: 999
      {{- end }}
      containers:
      - name: postgres
        image: {{ .Values.postgresql.image }}
        {{- if .Values.postgresql.tls.enabled }}
        args:
          - "-c"
          - "ssl=on"
          - '-c'
          - config_file=/etc/postgresql/postgresql.conf
          - '-c'
          - hba_file=/etc/postgresql/pg_hba.conf
        {{- end }}
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-postgres-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
          subPath: data
        - mountPath: /docker-entrypoint-initdb.d
          name: init-scripts
          readOnly: true
        {{- if .Values.postgresql.tls.enabled }}
        - name: config
          mountPath: /etc/postgresql/
        - name: postgres-tls
          readOnly: true
          mountPath: /tls
        {{- end }}
      volumes:
      {{- if .Values.postgresql.tls.enabled }}
      - name: config
        configMap:
          name: {{ .Release.Name }}-postgres-config
          items:
            - key: postgresql.conf
              path: postgresql.conf
            - key: pg_hba.conf
              path: pg_hba.conf
          defaultMode: 420
      - name: postgres-tls
        secret:
          secretName: postgres-tls
          defaultMode: 384
      {{- end }}
      - name: postgres-storage
        {{- if .Values.postgresql.pvc.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgres-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: init-scripts
        configMap:
          name: {{ .Release.Name }}-postgres-scripts
