apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-monitor-transform
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "monitor") | nindent 4 }}
data:
{{- range $path, $_ := (.Files.Glob "transform/pod/*") }}
  {{ trimPrefix "transform/pod/" $path }}: |
    {{- $.Files.Get $path | nindent 4 }}
{{ end }}
