apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-postgres-refresh-mv-cronjob
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}  
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: test
            app.kubernetes.io/instance: klustercost
            app.kubernetes.io/name: klustercost
            app.kubernetes.io/version: 1.16.0
        spec:
          containers:
          - env:
            - name: PGHOST
              value: {{ .Release.Name }}-postgres-service.{{ .Release.Namespace }}.svc.cluster.local
            - name: PGPORT
              value: {{ .Values.postgresql.port | quote }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: POSTGRES_DB
            image: {{ .Values.postgresql.clientImage }}
            imagePullPolicy: Always
            command: [ "psql", "-f", "/klustercost/statements.sql" ]
            name: klustercost-pg-mv-refresh
            resources:
              limits:
                cpu: "1"
                memory: 512Mi
              requests:
                cpu: 50m
                memory: 256Mi
            volumeMounts:
            - mountPath: /klustercost/statements.sql
              subPath: statements.sql
              name: update-materialized-views
          volumes:
          - name: update-materialized-views
            configMap:
              name: {{ .Release.Name }}-postgres-refresh-mv-configmap
          restartPolicy: OnFailure
