kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-price
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "price") | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5001
  selector:
    {{- include "klustercost.componentSelectorLabels" (dict "context" . "component" "price") | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
  internalTrafficPolicy: Cluster
