apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-price
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "price") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "klustercost.componentSelectorLabels" (dict "context" . "component" "price") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "klustercost.componentLabels" (dict "context" . "component" "price") | nindent 8 }}
    spec:
      {{- if .Values.imageRegistry.enabled }}
      imagePullSecrets:
        - name: {{ .Release.Name }}-registry-secret
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-price
          image: {{ .Values.price.image }}
          env:
            - name: PROVIDER
              value: {{ .Values.price.provider }}      
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.05"
              memory: 256Mi
          ports:
          - containerPort: 5001
