{{- if .Values.teams.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-teams-secret
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "teams-frontend") | nindent 4 }}
type: Opaque
data:
  CLIENT_ID: {{ .Values.teams.clientId | b64enc | quote }}
  TENANT_ID: {{ .Values.teams.tenantId | b64enc | quote }}
{{- end }}
