{{- if .Values.teams.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.teams.clientId }}
  name: azure-bot-sa
  namespace: klustercost
{{- end }}