{{- if .Values.wafrontend.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-wa-frontend
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ .Values.wafrontend.replicas }}
  selector:
    matchLabels:
      {{- include "klustercost.componentSelectorLabels" (dict "context" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "klustercost.componentLabels" (dict "context" . "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: kc-wab
          image: {{ .Values.wafrontend.image }}
          env:
            - name: VERIFY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-wa-frontend
                  key: VERIFY_TOKEN
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-wa-frontend
                  key: ACCESS_TOKEN
            - name: HOST_PORT
              value: "{{ .Values.wafrontend.targetPort }}"
            - name: MCP_CLIENT_ADDRESS
              value: http://{{ .Release.Name }}-mcp-client.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.mcp.client.port }}
            - name: TEMPLATE
              value: "{{ .Values.wafrontend.template }}"
            - name: TEMPLATE_CONTEXT
              value: "{{ .Values.wafrontend.templateContext }}"              
          resources:
            requests:
              cpu: {{ .Values.wafrontend.resources.requests.cpu }}
              memory: {{ .Values.wafrontend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.wafrontend.resources.limits.cpu }}
              memory: {{ .Values.wafrontend.resources.limits.memory }}
          ports:
            - containerPort: {{ .Values.wafrontend.targetPort }}
              protocol: TCP   
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.wafrontend.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.wafrontend.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 30                     
{{- end }}
