{{- if .Values.wafrontend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wa-frontend
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "frontend") | nindent 4 }}
type: Opaque
data:
  ACCESS_TOKEN: {{ .Values.wafrontend.accesstoken | b64enc | quote }}
  VERIFY_TOKEN: {{ .Values.wafrontend.verifytoken | b64enc | quote }}
{{- end }}
