{{- if .Values.wafrontend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wa-frontend
  labels:
    app: {{ .Release.Name }}-wa-frontend
type: Opaque
stringData:
  ACCESS_TOKEN: {{ .Values.wafrontend.accesstoken | quote }}
  VERIFY_TOKEN: {{ .Values.wafrontend.verifytoken | quote }}
{{- end }}