{{- if .Values.wafrontend.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-wa-frontend
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "frontend") | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.wafrontend.port }}
      targetPort: {{ .Values.wafrontend.targetPort }}
  selector:
    {{- include "klustercost.componentSelectorLabels" (dict "context" . "component" "frontend") | nindent 4 }}
  type: {{ .Values.wafrontend.serviceType }}
{{- end }}
