{{- if .Values.whatsappfrontend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-whatsapp-frontend
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "frontend") | nindent 4 }}
type: Opaque
data:
  ACCESS_TOKEN: {{ .Values.whatsappfrontend.accesstoken | default "" | b64enc | quote }}
  VERIFY_TOKEN: {{ .Values.whatsappfrontend.verifytoken | default "" | b64enc | quote }}
{{- end }}
