apiVersion: apps/v1
kind: Deployment
metadata:
  name: klustercost-price
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klustercost-price
  template:
    metadata:
      labels:
        app: klustercost-price
    spec:
      containers:
        - name: klustercost-price
          image: ghcr.io/klustercost/k8s/klustercost-price:latest
          env:
            - name: PROVIDER
              value: "azure"          
          resources:
            limits:
              cpu: "1"
              memory: 1024Mi
            requests:
              cpu: "0.05"
              memory: 1024Mi
          ports:
          - containerPort: 5001