{{- if .Values.mcp.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-mcp-client
  labels:
    {{- include "klustercost.componentLabels" (dict "context" . "component" "mcp-client") | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.mcp.client.port }}
      targetPort: {{ .Values.mcp.client.port }}
  selector:
    {{- include "klustercost.componentSelectorLabels" (dict "context" . "component" "mcp-client") | nindent 4 }}
  type: {{ .Values.mcp.client.serviceType }}
{{- end }}
