name: Create and publish MCP images

on:
  push:
    branches:
      - main
    paths:
      - mcp/**

  workflow_dispatch:

jobs:
  build-and-push-server:
    permissions:
      packages: write
    uses: ./.github/workflows/base_build_image.yaml
    with:
      registry: ghcr.io
      image_name: klustercost-mcp-server
      base_folder: mcp/server
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-client:
    permissions:
      packages: write
    uses: ./.github/workflows/base_build_image.yaml
    with:
      registry: ghcr.io
      image_name: klustercost-mcp-client
      base_folder: mcp/client
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
